# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b49782e187de847446a1771e4c6c0e8155a8521f690316139798e122fc18cf9b8adf78398eb83d774b525bc423bb0e9169a184b212f88511941092b857b9f8bd

test:
  secret_key_base: da96ed40079c2fb2da300f70123064c8093ea986a97905a6a365513f3197b4db5cc25faf0a0d7516f407c0330deb057f0257d7b6c33eda13aca0041e504b6023

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
